docs/schema.rst
lib/Index.js
lib/Utils.js
lib/form/Input.js
lib/table/Filter.js
lib/table/Header.js
lib/utils/schemaGetters.js
src/Index.js
src/Utils.js
src/form/Input.js
src/table/Filter.js
src/table/Header.js
src/utils/schemaGetters.js

ensure that schema custom overrides receive 'customProps' passed in

Add customprops

---

css/index.css
docs/schema.rst
lib/Edit.js
lib/form/Create.js
lib/form/Input.js
lib/input/inputComponent.js
lib/table/Filter.js
lib/utils/schemaGetters.js
src/Edit.js
src/form/Create.js
src/form/Input.js
src/input/inputComponent.js
src/table/Filter.js
src/utils/schemaGetters.js

[WIP] Add help text to fields

---

CHANGES.md
lib/Utils.js
lib/form/Breadcrumbs.js
lib/form/Create.js
lib/form/Input.js
lib/utils/schemaGetters.js
src/Utils.js
src/form/Breadcrumbs.js
src/form/Create.js
src/form/Input.js
src/utils/schemaGetters.js

do not pass formStack prop into override functions, is not neccessary

take away formStack from override functions

---

lib/table/Field.js
lib/table/Table.js
lib/utils/getDisplayValue.js
src/table/Field.js
src/table/Table.js
src/utils/getDisplayValue.js

the function getDisplayValue does not get the 'parentModelName' prop. take it away

fix-get-display-value-props

---

CHANGES.md
src/Pagination.js

pagination matches new magql update

Add pagination from new magql changes

---

CHANGES.md
src/Detail.js

Fixed CollapseTableIcon being set to FaAngleDown instead of FaAngleRight when collapsed

---

CHANGES.md
package-lock.json
package.json
src/Modal.js
src/PrintButton.js

Adds button that opens up browser print for an image
Uses print-js npm library: https://www.npmjs.com/package/print-js

Add print button to Modal

---

src/input/index.js

fixing bug from this PR https://github.com/autoinvent/conveyor/pull/44

bugfix: add className to input's string/textarea

---

CHANGES.md
src/Detail.js

Fixes https://github.com/autoinvent/conveyor/issues/46

changed logic to check if node is an empty object

---

CHANGES.md
package.json

Updating version numbers for a new publish.

updating version number only

---

src/main.js

allow export of DetailPagination

export detail pagination

---

src/delete/DeleteDetail.js

resolves https://github.com/autoinvent/conveyor/issues/69

returning a blank string if the Enum Label resolves to undefined

---

src/form/Input.js
src/table/Filter.js

resolves https://github.com/autoinvent/conveyor/issues/74

removing the undefined id variables from the keys

---

CHANGES.md
package-lock.json
package.json
src/form/Input.js
src/input/index.js
src/input/inputComponent.js
src/table/Field.js
src/table/Filter.js
src/utils/timezoneHelpers.js

Adds a DateTime input type for inputting a date with a specific time.

Add DateTime input type

---

src/form/Input.js

https://github.com/autoinvent/conveyor/issues/79

Issue 79: move field help and disable input to  InputCore

---

CHANGES.md
docs/customization/conveyor_css_classes.rst
docs/customization/index.rst
src/Alerts.js
src/CreateButton.js
src/Detail.js
src/Edit.js
src/Index.js
src/Modal.js
src/Pagination.js
src/Popover.js
src/PrintButton.js
src/Search.js
src/Tabs.js
src/Tooltip.js
src/TreeTable.js
src/delete/DeleteDetail.js
src/form/Breadcrumbs.js
src/form/Create.js
src/form/Input.js
src/input/inputComponent.js
src/table/Filter.js
src/table/Table.js

Adds class names to pretty much everything. 
closes #13

Add class names to common components

---

CHANGES.md
src/Detail.js
src/Index.js
src/NullComponent.js
src/Utils.js
src/form/Create.js
src/form/Input.js
src/table/Footer.js
src/table/Header.js
src/table/Table.js

#7 Doesn't quite use the solution suggested, but doing it with a null component cleans up more areas.
Also branched out internal lists to their own components.
Straight refactor

Refactors component Overrides Closing #7

---

CHANGES.md
css/index.css
docs/customization/conveyor_css_classes.rst
src/CreateButton.js
src/Detail.js
src/Index.js
src/Popover.js
src/PrintButton.js
src/Search.js
src/TreeTable.js
src/form/Breadcrumbs.js
src/form/Input.js
src/input/inputComponent.js
src/table/Filter.js
src/table/Footer.js
src/table/Header.js
src/table/Table.js

Pure refactor pr operating on just the styling.

move styling from react classes to css Closing #78

---

src/form/Input.js
src/input/inputComponent.js

fixes #12 
Popover function added to all available Input Types for Create
(Two commits since I changed from my Fork to this repo)

Create popover for Issue #12

---

src/table/Table.js

#80 
<THead> and <TFoot> were already exported
Exported remaining <TBody>

Export Table components

---

docs/components/dark_mode_toggle.rst
docs/customization/conveyor_css_classes.rst
src/DarkModeToggle.js
src/main.js

Adds dark mode component to conveyor
related to conveyor-redux: https://github.com/autoinvent/conveyor-redux/pull/64

DarkModeToggle.js added #98

---

CHANGES.md
css/index.css
css/styles.scss
css/styling.css
docs/customization/conveyor_css_classes.rst
package.json
src/Alerts.js
src/CreateButton.js
src/DarkModeToggle.js
src/Detail.js
src/Edit.js
src/Index.js
src/Modal.js
src/Pagination.js
src/PrintButton.js
src/Search.js
src/Tabs.js
src/Tooltip.js
src/TreeTable.js
src/delete/DeleteDetail.js
src/form/Breadcrumbs.js
src/form/Create.js
src/form/Input.js
src/table/Filter.js
src/table/Table.js
yarn.lock

In order to use the theming, add:
```
@import '../node_modules/@autoinvent/conveyor/css/index';
@import '../node_modules/@autoinvent/conveyor/css/styles.scss';
```
to wherever you have
```
@import '../node_modules/@autoinvent/conveyor/css/index';
```

Extract bootstrap to conveyor theme

---

src/CreateButton.js
src/Detail.js
src/DetailLink.js
src/Edit.js
src/Index.js
src/Modal.js
src/Pagination.js
src/delete/DeleteDetail.js
src/form/Create.js
src/form/Input.js
src/table/Field.js
src/table/Filter.js
src/table/Table.js

Documents large sections of conveyor code. Basically, most of the stuff made available through main.js, except what itechify is doing.

Documentation hierarchy

---

CHANGES.md
package.json
src/CreateButton.tsx
src/DarkModeToggle.tsx
src/Detail.tsx
src/DetailLink.tsx
src/Edit.js
src/NullComponent.js
src/NullComponent.tsx
src/PrintButton.tsx
src/Utils.ts
src/delete/DeleteDetail.js
src/form/Input.js
yarn.lock

Converts the detail page to typescript

Convert typescript detail page

---

package.json
src/CreateButton.tsx
src/DarkModeToggle.tsx
src/DetailLink.tsx
src/NullComponent.js
src/NullComponent.tsx
src/PrintButton.tsx
src/Utils.ts

Got NullComponent, DarkModeToggle, CreateButton, DeleteLink, PrintButton and Utils.js converted.
Not that reduplicating the work wouldn't be a snap. They're very small and simple files.

convert to typescript, little components

---

src/Detail.js

- Fixed issue where deleting from Detail would not redirect the user and remain on Detail page with null values.
- Likely an update caused this issue

Delete Detail redirects to Index

---

src/form/Breadcrumbs.tsx
src/form/Create.tsx
src/form/Input.tsx
yarn.lock

Also had to convert src/input/index.js because of a dependency on `FlexibleInput`.
Feeling unsure about the gratuitous use of the `any` type. Open to suggestions if more strict typing should be used.

Convert files in "forms" directory to Typescript

---

src/Search.js
src/main.js

fixes #101  
- After entering a query, press the 'Search' Link button and it'll redirect you to a new page with the results listed similarly to the dropdown
- Note: Considering to add a Filter button in a separate PR if time allows
- Setup SearchContainer.js in main project
```
import { Search, SearchResults } from '@autoinvent/conveyor'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import {
searchQueryTextChange,
searchQueryLinkClicked,
onTriggerSearch,
onSearchBlur
} from '@autoinvent/conveyor-redux/lib/actions'
import {
selectSearchDropdown,
selectSearchQueryText,
selectSearchEntries
} from '@autoinvent/conveyor-redux/lib/utils/search'
/********** Search Navbar **********/
const mapStateToProps = (state) => ({
queryText: selectSearchQueryText(state), …
```

Basic search page

---

.eslintrc.js
src/Popover.tsx
src/Tabs.tsx
src/Tooltip.tsx
src/TreeTable.tsx

TreeTable, Tooltip, Tabs, and Popover.
Going to rebase into a single commit, but opening a pr now to see and confirm if it is successful.

Typescript Conversion

---

src/Detail.tsx
src/Edit.tsx
src/Index.tsx
src/Tabs.tsx
src/form/Create.tsx
src/form/Input.tsx
src/table/Table.tsx

Remove's orphaned prop from a feature that we are no longer planning on using.

remove failedValidation prop

---

.babelrc
__tests__/FlexibleInput.test.tsx
__tests__/ModelOverrides.test.tsx
__tests__/SchemaDefaults.test.ts
__tests__/__mocks__/mock_data/schema.js
__tests__/sanity.test.ts
babel.config.js
jest.config.js
package.json
yarn.lock

Babel dependencies added back into project. Fixed some tests cases that are outdated.
One getter test case requires conveyor-schema changes.

Combining all of the labels for fixing jest into one.

---

src/Search.tsx

Addresses 2nd item in this issue comment: https://github.com/autoinvent/conveyor/issues/152#issue-939107676
Paired with https://github.com/autoinvent/conveyor-redux/pull/74

Use displayLabel from redux store for filter label

---

.github/workflows/CI.yml

This branch is for testing adding cache to workflow action.
Please don't merge into main just yet.

Testing adding using cache with git actions
